name: Pull Request
description: Template for pull requests
body:
  - "## What changes have been made?"
  - ""
  - "[Provide a short description of the changes.]"
  - ""
  - "## Related Issues or Tasks"
  - ""
  - "[Link to any related issues or tasks.]"
  - ""
  - "## Checklist"
  - ""
  - "- [ ] Code has been linted."
  - "- [ ] Tests have been added (if applicable)."
  - "- [ ] Documentation has been updated (if applicable)."
