name: "✨ Feature Request"
description: "Suggest a new feature or enhancement"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Summary
  - type: textarea
    id: feature-summary
    attributes:
      label: "Summary"
      description: "Provide a short summary of the feature or enhancement."
      placeholder: "Briefly describe the feature..."
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this feature is needed and the problem it solves."
      placeholder: "Why is this feature important?"
  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Describe the solution or approach you suggest."
      placeholder: "How would you implement this feature?"
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "List any alternative solutions or features you considered."
      placeholder: "Other options you considered..."
  - type: input
    id: environment
    attributes:
      label: "Environment (OS, Node.js, pnpm, Project version)"
      description: "Provide details about your environment to help with debugging."
      placeholder: "e.g. Ubuntu 20.04, Node.js 16.13.0, pnpm 6.14.5, v1.2.3"
